-- AlterTable
ALTER TABLE "Models" ADD COLUMN     "age" INTEGER DEFAULT 0,
ADD COLUMN     "heightImperial" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "heightMetric" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "weightImperial" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "weightMetric" DOUBLE PRECISION DEFAULT 0;
